# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value


services:
    
    domain.service.shift_scheduler:
        class: Domain\Shifts\Services\ShiftScheduler 
        arguments:
            - "@persistence.repositories.in_memory.shift"
            - "@persistence.repositories.in_memory.user"        
            - "@events.in_memory.event_dispatcher"
#
#    domain.service.shift_provider:
#        class: Domain\Shifts\Services\ShiftProvider 
#        arguments:
#            - "@persistence.repositories.doctrine.shift"
                    
    persistence.repositories.in_memory.user:
        class: AppBundle\Persistence\InMemory\InMemoryUserRepository
        
    persistence.repositories.in_memory.shift:
        class: AppBundle\Persistence\InMemory\InMemoryShiftRepository
                
    events.in_memory.event_dispatcher:
        class: AppBundle\Event\InMemoryEventDispatcher
            
#    persistence.repositories.doctrine.shift:
#        class: AppBundle\Persistence\Doctrine\DoctrineShiftRepository
#        arguments:
#            - "@doctrine.orm.default_entity_manager"            
#            
#    event.dispatcher:
#        class: AppBundle\Event\SymfonyEventDispatcher
#
#    
#    transformers.shift:
#        class: AppBundle\Transformers\ShiftTransformer
