# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value


services:
    
    domain.service.shift_scheduler:
        class: Domain\Shifts\Services\ShiftScheduler 
        arguments:
            - "@persistence.repositories.doctrine.shift"
            - "@persistence.repositories.doctrine.employee"
            - "@event.dispatcher"

    domain.service.shift_provider:
        class: Domain\Shifts\Services\ShiftProvider 
        arguments:
            - "@persistence.repositories.doctrine.shift"
                    
    persistence.repositories.doctrine.employee:
        class: AppBundle\Persistence\Doctrine\DoctrineEmployeeRepository
        arguments:
            - "@doctrine.orm.default_entity_manager"
            
    persistence.repositories.doctrine.shift:
        class: AppBundle\Persistence\Doctrine\DoctrineShiftRepository
        arguments:
            - "@doctrine.orm.default_entity_manager"            
            
    event.dispatcher:
        class: AppBundle\Event\SymfonyEventDispatcher

    
    transformers.shift:
        class: AppBundle\Transformers\ShiftTransformer
