Domain\Employees\Employee:
    type: entity
    table: employee
    id:
        id:
            type: uuid
            generator:
                strategy: CUSTOM 
            customIdGenerator:
                class: Ramsey\Uuid\Doctrine\UuidGenerator
    fields:
        name:
            type: string
            length: 100
            
        email:
            type: string
            length: 100
            unique: true

    manyToOne:
        position:
            targetEntity: Domain\Employees\Position
            joinColumn:
                name: position_id
                referencedColumnName: id
