Domain\Shifts\Shift:
    type: entity
    table: shift
    id:
        id:
            type: uuid
            generator:
                strategy: CUSTOM 
            customIdGenerator:
                class: Ramsey\Uuid\Doctrine\UuidGenerator
    fields:
        startTime:
            type: datetime
            
        endTime:
            type: datetime

        status:
            type: string
            length: 100            
            

    manyToOne:
        employee:
            targetEntity: Domain\Employees\Employee
            joinColumn:
                name: employee_id
                referencedColumnName: id
